# Generated by Django 5.2.8 on 2025-11-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='monthly_budget',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='expected_rent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='faculty',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='has_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='max_commute_min',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='rent_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='smoker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='student_id',
            field=models.CharField(default='S0000', max_length=10),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='university',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='year',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
